# Generated by Django 6.0.4 on 2026-05-26 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_article_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='word_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
