# Generated by Django 6.0.4 on 2026-05-26 15:49
from django.utils import timezone
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_article_word_count'),
    ]

    def create_superuser(apps, schema_editor):
        from django.contrib.auth import get_user_model
        
        User = get_user_model()

        if User.objects.exists():
            return
        
        superuser = User.objects.create_superuser(
            username="example_username",
            email="example@example.com",
            password="example_password",
            last_login=timezone.now(),
        )
        superuser.save()

    operations = [
        migrations.RunPython(create_superuser)
    ]
