# Generated by Django 6.0.4 on 2026-05-26 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20260526_2119'),
    ]

    operations = [
    ]
