# Generated by Django 6.0.4 on 2026-06-22 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_userprofile_managers_alter_userprofile_email'),
    ]

    operations = [
    ]
